spring:
  application:
    name: deal
  profiles:
    active: prod

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/deal_db
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer:  org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.value.default.type: ru.neoflex.kubrak.deal.dto.EmailMessageDto

calculator:
  service:
    base-url: http://calculator
    calc-credit-url: /calculator/calc
    calc-offers-url: /calculator/offers


deal:
  kafka:
    topic:
      finish-registration: finish-registration
      create-documents: create-documents
      send-documents: send-documents
      send-ses: send-ses
      credit-issued: credit-issued
      statement-denied:  statement-denied

logging:
  level:
    root: info
  pattern:
    console: "%d{HH:mm:ss} %-5level %logger{36} - %msg%n"