version: '3.8'

services:

  postgres-base:
    image: postgres:13
    container_name: some_postgres_base
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: deal_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d deal_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - credit-bank-network

  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - credit-bank-network

  kafka:
    image: confluentinc/cp-kafka:5.5.0
    hostname: kafka
    container_name: kafka
    ports:
      - "29092:29092"
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - credit-bank-network

  calculator-service:
    build:
      context: .
      dockerfile: calculator/Dockerfile
    container_name: calculator-service
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - credit-bank-network

  deal-service:
    build:
      context: .
      dockerfile: deal/Dockerfile
    container_name: deal-service
    ports:
      - "8082:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-base:5432/deal_db
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      CALCULATOR_SERVICE_BASE_URL: http://calculator-service:8080
    depends_on:
      - postgres-base
      - kafka
      - calculator-service
    networks:
      - credit-bank-network

  # Statement service
  statement-service:
    build:
      context: .
      dockerfile: statement/Dockerfile
    container_name: statement-service
    ports:
      - "8083:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DEAL_SERVICE_BASE_URL: http://deal-service:8080
    depends_on:
      - deal-service
    networks:
      - credit-bank-network

  dossier-service:
    build:
      context: .
      dockerfile: dossier/Dockerfile
    container_name: dossier-service
    ports:
      - "8084:8080"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      SPRING_MAIL_HOST: smtp.neoflex.ru
      SPRING_MAIL_PORT: 465
      SPRING_MAIL_USERNAME: ${EMAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${EMAIL_PASSWORD}
    depends_on:
      - kafka
    networks:
      - credit-bank-network

  gateway-service:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    container_name: gateway-service
    ports:
      - "8085:8080"
    environment:
      CLIENT_SERVICE_STATEMENT_BASE_URL: http://statement-service:8080
      CLIENT_SERVICE_DEAL_BASE_URL: http://deal-service:8080
    depends_on:
      - deal-service
      - statement-service
    networks:
      - credit-bank-network

networks:
  credit-bank-network:
    driver: bridge