spring:
  application:
    name: gateway

client:
  service:
    statement:
      base-url: http://statement-service:8080
      endpoints:
        get-offers: /statement
        select-offer: /statement/offer
    deal:
      base-url: http://deal-service:8080
      endpoints:
        calculate: /deal/calculate/{statementId}
        send-documents: /deal/document/{statementId}/send
        sign-documents: /deal/document/{statementId}/sign
        verify-code: /deal/document/{statementId}/code
        get-statement: /deal/admin/statement/{statementId}
        get-all-statements: /deal/admin/statement