server:
  port: 8090

spring:
  application:
    name: calculator

logging:
  level:
    root: INFO
    com.example.calculator: DEBUG
  pattern:
    console: "%d{HH:mm:ss} %-5level %logger{36} - %msg%n"