spring:
    application:
        name: dossier

    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            group-id: dossier-group
            key-deserializer:  org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            properties:
                spring.json.value.default.type: ru.neoflex.kubrak.dossier.dto.EmailMessageDto

    mail:
        host: smtp.neoflex.ru
        port: 587
        username: login
        password: password

dossier:
    kafka:
        topic:
            finish-registration: finish-registration
            create-documents: create-documents
            send-documents: send-documents
            send-ses: send-ses
            credit-issued: credit-issued
            statement-denied:  statement-denied

